### ISSUE TITLE
Can't understand whats happening

### ISSUE THREAD

**Issue by shuvro-zz** [DayNetCo/DocMan#1]
After installing 
![sDocman](https://user-images.githubusercontent.com/74450/67023872-4e39b700-f125-11e9-8def-42313c198868.png)

Registering a user
then how to proceed?
![sDocman2](https://user-images.githubusercontent.com/74450/67024048-92c55280-f125-11e9-9747-182dba9edcad.png)

**Comment by mbougarne** [comment]
This is incomplete project, it is in progress.
